In [8]:
import numpy as np

# Define two custom numpy arrays A and B (as per lecture slides)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 5, 9], [10, 11, 12]])

# 1. Stack Vertically and Horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  5  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  5  9]
 [ 4  5  6 10 11 12]]


In [9]:
# 2. Find Common Elements Between A and B
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [5]


In [10]:
# 3. Extract Numbers from A Within a Specific Range (e.g., between 5 and 10)
filtered_A = A[(A >= 5) & (A <= 10)]
print("Filtered Numbers from A (Between 5 and 10):", filtered_A)

Filtered Numbers from A (Between 5 and 10): [5 6]


In [11]:
# 4. Load and Filter `iris_2d` Dataset Based on Conditions
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)

Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [ ]:
import pandas as pd

# 1. Load and Filter 'Manufacturer', 'Model', and 'Type' for Every 20th Row
df = pd.read_csv('Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Filtered Data (Every 20th Row):\n", filtered_df)


Filtered Data (Every 20th Row):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [13]:
# 2. Replace Missing Values in 'Min.Price' and 'Max.Price' with Their Respective Mean
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda col: col.fillna(col.mean()))
print("\nData after replacing NaN values in Min.Price & Max.Price:")
print(df[['Min.Price', 'Max.Price']].head())
print("\nMissing Values in Min.Price and Max.Price (After Replacement):")
print(df[['Min.Price', 'Max.Price']].isnull().sum())



Data after replacing NaN values in Min.Price & Max.Price:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

Missing Values in Min.Price and Max.Price (After Replacement):
Min.Price    0
Max.Price    0
dtype: int64


In [14]:
# 3. Get Rows Where Row Sum > 100
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_rows = df_random[df_random.sum(axis=1) > 100]
print("\nRows with Sum Greater than 100:\n", filtered_rows)


Rows with Sum Greater than 100:
      0   1   2   3
2   28  37  29  16
3   36  35  36  33
7   27  35  37  17
10  35  23  39  33
13  25  25  28  25
