In [3]:
import numpy as np

# Define two custom numpy arrays A and B (as per lecture slides)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 5, 9], [10, 11, 12]])

# 1. Stack Vertically and Horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  5  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  5  9]
 [ 4  5  6 10 11 12]]


In [4]:
# 2. Find Common Elements Between A and B
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [5]


In [5]:
# 3. Extract Numbers from A Within a Specific Range (e.g., between 5 and 10)
filtered_A = A[(A >= 5) & (A <= 10)]
print("Filtered Numbers from A (Between 5 and 10):", filtered_A)

Filtered Numbers from A (Between 5 and 10): [5 6]


In [6]:
# 4. Load and Filter `iris_2d` Dataset Based on Conditions
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)

FileNotFoundError: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

In [7]:
import pandas as pd

# 1. Load and Filter 'Manufacturer', 'Model', and 'Type' for Every 20th Row
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# df = pd.read_csv('Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Filtered Data (Every 20th Row):\n", filtered_df)


Filtered Data (Every 20th Row):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [8]:
# 2. Replace Missing Values in 'Min.Price' and 'Max.Price' with Their Respective Mean
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda col: col.fillna(col.mean()))
print("\nData after replacing NaN values in Min.Price & Max.Price:")
print(df[['Min.Price', 'Max.Price']].head())



Data after replacing NaN values in Min.Price & Max.Price:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [10]:
# 3. Get Rows Where Row Sum > 100
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filtered_rows = df_random[df_random.sum(axis=1) > 100]
print("\nRows with Sum Greater than 100:\n", filtered_rows)


Rows with Sum Greater than 100:
      0   1   2   3
0   39  37  12  19
2   27  39  33  25
4   30  33  32  39
6   23  22  25  38
10  39  28  16  27
12  37  32  20  17
14  31  22  31  18
